

Aladdin Free Public License
(Version 8, November 18, 1999)

Copyright (C) 1994, 1995, 1997, 1998, 1999 Aladdin Enterprises,
Menlo Park, California, U.S.A. All rights reserved.

NOTE: This License is not the same as any of the GNU Licenses published by the Free Software Foundation. Its terms are substantially different from those of the GNU Licenses. If you are familiar with the GNU Licenses, please read this license with extra care.

Aladdin Enterprises hereby grants to anyone the permission to apply this License to their own work, as long as the entire License (including the above notices and this paragraph) is copied with no changes, additions, or deletions except for changing the first paragraph of Section 0 to include a suitable description of the work to which the license is being applied and of the person or entity that holds the copyright in the work, and, if the License is being applied to a work created in a country other than the United States, replacing the first paragraph of Section 6 with an appropriate reference to the laws of the appropriate country.

    0. Subject Matter
    This License applies to the computer program known as "Aladdin Ghostscript." The "Program", below, refers to such program. The Program is a copyrighted work whose copyright is held by Aladdin Enterprises (the "Licensor"). Please note that Aladdin Ghostscript is neither the program known as "GNU Ghostscript" nor the version of Ghostscript available for commercial licensing from Artifex Software Inc.

    A "work based on the Program" means either the Program or any derivative work of the Program, as defined in the United States Copyright Act of 1976, such as a translation or a modification.

    BY MODIFYING OR DISTRIBUTING THE PROGRAM (OR ANY WORK BASED ON THE PROGRAM), YOU INDICATE YOUR ACCEPTANCE OF THIS LICENSE TO DO SO, AND ALL ITS TERMS AND CONDITIONS FOR COPYING, DISTRIBUTING OR MODIFYING THE PROGRAM OR WORKS BASED ON IT. NOTHING OTHER THAN THIS LICENSE GRANTS YOU PERMISSION TO MODIFY OR DISTRIBUTE THE PROGRAM OR ITS DERIVATIVE WORKS. THESE ACTIONS ARE PROHIBITED BY LAW. IF YOU DO NOT ACCEPT THESE TERMS AND CONDITIONS, DO NOT MODIFY OR DISTRIBUTE THE PROGRAM.
    1. Licenses.
    Licensor hereby grants you the following rights, provided that you comply with all of the restrictions set forth in this License and provided, further, that you distribute an unmodified copy of this License with the Program:
        (a) You may copy and distribute literal (i.e., verbatim) copies of the Program's source code as you receive it throughout the world, in any medium.
        (b) You may modify the Program, create works based on the Program and distribute copies of such throughout the world, in any medium.
    2. Restrictions.
    This license is subject to the following restrictions:
        (a) Distribution of the Program or any work based on the Program by a commercial organization to any third party is prohibited if any payment is made in connection with such distribution, whether directly (as in payment for a copy of the Program) or indirectly (as in payment for some service related to the Program, or payment for some product or service that includes a copy of the Program "without charge"; these are only examples, and not an exhaustive enumeration of prohibited activities). The following methods of distribution involving payment shall not in and of themselves be a violation of this restriction:
            (i) Posting the Program on a public access information storage and retrieval service for which a fee is received for retrieving information (such as an on-line service), provided that the fee is not content-dependent (i.e., the fee would be the same for retrieving the same volume of information consisting of random data) and that access to the service and to the Program is available independent of any other product or service. An example of a service that does not fall under this section is an on-line service that is operated by a company and that is only available to customers of that company. (This is not an exhaustive enumeration.)
            (ii) Distributing the Program on removable computer-readable media, provided that the files containing the Program are reproduced entirely and verbatim on such media, that all information on such media be redistributable for non-commercial purposes without charge, and that such media are distributed by themselves (except for accompanying documentation) independent of any other product or service. Examples of such media include CD-ROM, magnetic tape, and optical storage media. (This is not intended to be an exhaustive list.) An example of a distribution that does not fall under this section is a CD-ROM included in a book or magazine. (This is not an exhaustive enumeration.)
        (b) Activities other than copying, distribution and modification of the Program are not subject to this License and they are outside its scope. Functional use (running) of the Program is not restricted, and any output produced through the use of the Program is subject to this license only if its contents constitute a work based on the Program (independent of having been made by running the Program).
        (c) You must meet all of the following conditions with respect to any work that you distribute or publish that in whole or in part contains or is derived from the Program or any part thereof ("the Work"):
            (i) If you have modified the Program, you must cause the Work to carry prominent notices stating that you have modified the Program's files and the date of any change. In each source file that you have modified, you must include a prominent notice that you have modified the file, including your name, your e-mail address (if any), and the date and purpose of the change;
            (ii) You must cause the Work to be licensed as a whole and at no charge to all third parties under the terms of this License;
            (iii) If the Work normally reads commands interactively when run, you must cause it, at each time the Work commences operation, to print or display an announcement including an appropriate copyright notice and a notice that there is no warranty (or else, saying that you provide a warranty). Such notice must also state that users may redistribute the Work only under the conditions of this License and tell the user how to view the copy of this License included with the Work. (Exceptions: if the Program is interactive but normally prints or displays such an announcement only at the request of a user, such as in an "About box", the Work is required to print or display the notice only under the same circumstances; if the Program itself is interactive but does not normally print such an announcement, the Work is not required to print an announcement.);
            (iv) You must accompany the Work with the complete corresponding machine-readable source code, delivered on a medium customarily used for software interchange. The source code for a work means the preferred form of the work for making modifications to it. For an executable work, complete source code means all the source code for all modules it contains, plus any associated interface definition files, plus the scripts used to control compilation and installation of the executable code. If you distribute with the Work any component that is normally distributed (in either source or binary form) with the major components (compiler, kernel, and so on) of the operating system on which the executable runs, you must also distribute the source code of that component if you have it and are allowed to do so;
            (v) If you distribute any written or printed material at all with the Work, such material must include either a written copy of this License, or a prominent written indication that the Work is covered by this License and written instructions for printing and/or displaying the copy of the License on the distribution medium;
            (vi) You may not impose any further restrictions on the recipient's exercise of the rights granted herein.

            If distribution of executable or object code is made by offering the equivalent ability to copy from a designated place, then offering equivalent ability to copy the source code from the same place counts as distribution of the source code, even though third parties are not compelled to copy the source code along with the object code.
    3. Reservation of Rights.
    No rights are granted to the Program except as expressly set forth herein. You may not copy, modify, sublicense, or distribute the Program except as expressly provided under this License. Any attempt otherwise to copy, modify, sublicense or distribute the Program is void, and will automatically terminate your rights under this License. However, parties who have received copies, or rights, from you under this License will not have their licenses terminated so long as such parties remain in full compliance.
    4. Other Restrictions.
    If the distribution and/or use of the Program is restricted in certain countries for any reason, Licensor may add an explicit geographical distribution limitation excluding those countries, so that distribution is permitted only in or among countries not thus excluded. In such case, this License incorporates the limitation as if written in the body of this License.
    5. Limitations.
    THE PROGRAM IS PROVIDED TO YOU "AS IS," WITHOUT WARRANTY. THERE IS NO WARRANTY FOR THE PROGRAM, EITHER EXPRESSED OR IMPLIED, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT OF THIRD PARTY RIGHTS. THE ENTIRE RISK AS TO THE QUALITY AND PERFORMANCE OF THE PROGRAM IS WITH YOU. SHOULD THE PROGRAM PROVE DEFECTIVE, YOU ASSUME THE COST OF ALL NECESSARY SERVICING, REPAIR OR CORRECTION.

    IN NO EVENT UNLESS REQUIRED BY APPLICABLE LAW OR AGREED TO IN WRITING WILL LICENSOR, OR ANY OTHER PARTY WHO MAY MODIFY AND/OR REDISTRIBUTE THE PROGRAM AS PERMITTED ABOVE, BE LIABLE TO YOU FOR DAMAGES, INCLUDING ANY GENERAL, SPECIAL, INCIDENTAL OR CONSEQUENTIAL DAMAGES ARISING OUT OF THE USE OR INABILITY TO USE THE PROGRAM (INCLUDING BUT NOT LIMITED TO LOSS OF DATA OR DATA BEING RENDERED INACCURATE OR LOSSES SUSTAINED BY YOU OR THIRD PARTIES OR A FAILURE OF THE PROGRAM TO OPERATE WITH ANY OTHER PROGRAMS), EVEN IF SUCH HOLDER OR OTHER PARTY HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.
    6. General.

    This License is governed by the laws of the State of California, U.S.A., excluding choice of law rules.

    If any part of this License is found to be in conflict with the law, that part shall be interpreted in its broadest meaning consistent with the law, and no other parts of the License shall be affected.

    For United States Government users, the Program is provided with RESTRICTED RIGHTS. If you are a unit or agency of the United States Government or are acquiring the Program for any such unit or agency, the following apply:

    If the unit or agency is the Department of Defense ("DOD"), the Program and its documentation are classified as "commercial computer software" and "commercial computer software documentation" respectively and, pursuant to DFAR Section 227.7202, the Government is acquiring the Program and its documentation in accordance with the terms of this License. If the unit or agency is other than DOD, the Program and its documentation are classified as "commercial computer software" and "commercial computer software documentation" respectively and, pursuant to FAR Section 12.212, the Government is acquiring the Program and its documentation in accordance with the terms of this License.




Aladdin Free Public License
(versão 8, 18 de novembro de 1999)

Copyright (C) 1994, 1995, 1997, 1998, 1999 Aladdin Enterprises,
Menlo Park, Califórnia, EUA Todos os direitos reservados.

NOTA: Esta licença não é igual a nenhuma das licenças GNU publicadas pela Free Software Foundation. Seus termos são substancialmente diferentes daqueles das Licenças GNU. Se você está familiarizado com as licenças GNU, leia esta licença com cuidado extra.

A Aladdin Enterprises concede a qualquer pessoa a permissão de aplicar esta Licença ao seu próprio trabalho, desde que toda a Licença (incluindo os avisos acima e este parágrafo) seja copiada sem alterações, acréscimos ou exclusões, exceto para alterar o primeiro parágrafo da Seção 0 para incluir uma descrição adequada da obra à qual a licença está sendo aplicada e da pessoa ou entidade que detém os direitos autorais da obra e, se a Licença estiver sendo aplicada a uma obra criada em um país diferente dos Estados Unidos , substituindo o primeiro parágrafo da Seção 6 por uma referência apropriada às leis do país apropriado.

    0. Assunto
    Esta Licença se aplica ao programa de computador conhecido como "Aladdin Ghostscript". O "Programa", abaixo, refere-se a esse programa. O Programa é um trabalho protegido por direitos autorais cujos direitos autorais pertencem à Aladdin Enterprises (o "Licenciante"). Observe que Aladdin Ghostscript não é o programa conhecido como "GNU Ghostscript" nem a versão do Ghostscript disponível para licenciamento comercial da Artifex Software Inc.

    Um "trabalho baseado no Programa" significa o Programa ou qualquer trabalho derivado do Programa, conforme definido na Lei de Direitos Autorais dos Estados Unidos de 1976, como uma tradução ou modificação.

    AO MODIFICAR OU DISTRIBUIR O PROGRAMA (OU QUALQUER TRABALHO COM BASE NO PROGRAMA), VOCÊ INDICA SUA ACEITAÇÃO DESTA LICENÇA PARA FAZER ISSO, E TODOS OS SEUS TERMOS E CONDIÇÕES PARA COPIAR, DISTRIBUIR OU MODIFICAR O PROGRAMA OU TRABALHOS COM BASE Nele. NADA ALÉM DESTA LICENÇA CONCEDE A VOCÊ PERMISSÃO PARA MODIFICAR OU DISTRIBUIR O PROGRAMA OU SUAS OBRAS DERIVATIVAS. ESTAS AÇÕES SÃO PROIBIDAS POR LEI. SE VOCÊ NÃO ACEITAR ESTES TERMOS E CONDIÇÕES, NÃO MODIFIQUE OU DISTRIBUA O PROGRAMA.
    1. Licenças.
    O Licenciante concede a você os seguintes direitos, desde que você cumpra com todas as restrições estabelecidas nesta Licença e desde que, além disso, distribua uma cópia não modificada desta Licença com o Programa:
        (a) Você pode copiar e distribuir cópias literais (ou seja, literalmente) do código-fonte do Programa à medida que o recebe em todo o mundo, em qualquer meio.
        (b) Você pode modificar o Programa, criar trabalhos baseados no Programa e distribuir cópias de tais em todo o mundo, em qualquer meio.
    2. Restrições.
    Esta licença está sujeita às seguintes restrições:
        (a) A distribuição do Programa ou qualquer trabalho baseado no Programa por uma organização comercial a terceiros é proibida se qualquer pagamento for feito em conexão com essa distribuição, seja diretamente (como no pagamento por uma cópia do Programa) ou indiretamente (como no pagamento por algum serviço relacionado ao Programa, ou pagamento por algum produto ou serviço que inclua uma cópia do Programa "sem encargos"; estes são apenas exemplos e não uma enumeração exaustiva de atividades proibidas). Os seguintes métodos de distribuição envolvendo pagamento não devem, por si só, ser uma violação desta restrição:
            (i) Publicar o Programa em um serviço de armazenamento e recuperação de informações de acesso público pelo qual uma taxa é recebida para recuperar informações (como um serviço on-line), desde que a taxa não seja dependente do conteúdo (ou seja, a taxa seria o mesmo para recuperar o mesmo volume de informações consistindo em dados aleatórios) e que o acesso ao serviço e ao Programa está disponível independentemente de qualquer outro produto ou serviço. Um exemplo de serviço que não se enquadra nesta seção é um serviço on-line operado por uma empresa e que está disponível apenas para clientes dessa empresa. (Esta não é uma enumeração exaustiva.)
            (ii) Distribuir o Programa em mídia legível por computador removível, desde que os arquivos que contenham o Programa sejam reproduzidos inteiramente e literalmente em tal mídia, que todas as informações em tal mídia sejam redistribuíveis para fins não comerciais sem custo, e que tal mídia seja distribuída por si mesmas (exceto para a documentação que o acompanha) independente de qualquer outro produto ou serviço. Exemplos de tais mídias incluem CD-ROM, fita magnética e mídia de armazenamento ótico. (Esta lista não tem a intenção de ser exaustiva.) Um exemplo de distribuição que não se enquadra nesta seção é um CD-ROM incluído em um livro ou revista. (Esta não é uma enumeração exaustiva.)
        (b) Atividades diferentes de cópia, distribuição e modificação do Programa não estão sujeitas a esta Licença e estão fora de seu escopo. O uso funcional (execução) do Programa não é restrito e qualquer saída produzida por meio do uso do Programa está sujeita a esta licença apenas se seu conteúdo constituir um trabalho baseado no Programa (independente de ter sido gerado pela execução do Programa).
        (c) Você deve atender a todas as seguintes condições com relação a qualquer trabalho que você distribua ou publique que, no todo ou em parte, contenha ou seja derivado do Programa ou de qualquer parte dele ("o Trabalho"):
            (i) Se você modificou o Programa, você deve fazer com que o Trabalho contenha avisos visíveis afirmando que você modificou os arquivos do Programa e a data de qualquer alteração. Em cada arquivo de origem que você modificou, você deve incluir um aviso em destaque de que você modificou o arquivo, incluindo seu nome, seu endereço de e-mail (se houver) e a data e o propósito da alteração;
            (ii) Você deve fazer com que a Obra seja licenciada como um todo e sem nenhum custo para todos os terceiros sob os termos desta Licença;
            (iii) Se a Obra normalmente lê comandos interativamente ao ser executada, você deve fazer com que, a cada vez que a Obra começar a operação, imprima ou exiba um anúncio incluindo um aviso de direitos autorais apropriado e um aviso de que não há garantia (ou então, dizendo que você fornece uma garantia). Tal notificação também deve declarar que os usuários podem redistribuir a Obra apenas sob as condições desta Licença e informar ao usuário como visualizar a cópia desta Licença incluída com a Obra. (Exceções: se o Programa é interativo, mas normalmente imprime ou exibe tal anúncio apenas a pedido de um usuário, como em uma "caixa Sobre",o Trabalho é obrigado a imprimir ou exibir o aviso apenas nas mesmas circunstâncias; se o Programa em si é interativo, mas normalmente não imprime tal anúncio, o Trabalho não é obrigado a imprimir um anúncio.);
            (iv) Você deve acompanhar o Trabalho com o código-fonte completo legível por máquina correspondente, entregue em um meio normalmente usado para intercâmbio de software. O código-fonte de uma obra significa a forma preferida da obra para fazer modificações nela. Para um trabalho executável, código-fonte completo significa todo o código-fonte para todos os módulos que ele contém, mais quaisquer arquivos de definição de interface associados, mais os scripts usados ​​para controlar a compilação e instalação do código executável. Se você distribuir com o Trabalho qualquer componente normalmente distribuído (na forma de origem ou binária) com os componentes principais (compilador, kernel e assim por diante) do sistema operacional em que o executável é executado,você também deve distribuir o código-fonte desse componente se o tiver e tiver permissão para fazê-lo;
            (v) Se você distribuir qualquer material escrito ou impresso com a Obra, tal material deve incluir uma cópia escrita desta Licença, ou uma indicação escrita proeminente de que a Obra é coberta por esta Licença e instruções escritas para impressão e / ou exibir a cópia da Licença no meio de distribuição;
            (vi) Você não pode impor quaisquer outras restrições ao exercício do destinatário dos direitos aqui concedidos.

            Se a distribuição do código executável ou objeto for feita oferecendo a capacidade equivalente de copiar de um local designado, então oferecer capacidade equivalente de copiar o código-fonte do mesmo lugar conta como distribuição do código-fonte, mesmo que terceiros não sejam obrigados a copie o código-fonte junto com o código-objeto.
    3. Reserva de direitos.
    Nenhum direito é concedido ao Programa, exceto conforme expressamente estabelecido neste documento. Você não pode copiar, modificar, sublicenciar ou distribuir o Programa, exceto conforme expressamente fornecido nesta Licença. Qualquer tentativa de copiar, modificar, sublicenciar ou distribuir o Programa é nula e encerrará automaticamente seus direitos sob esta Licença. No entanto, as partes que receberam cópias, ou direitos, de você sob esta Licença não terão suas licenças rescindidas, desde que essas partes permaneçam em total conformidade.
    4. Outras restrições.
    Se a distribuição e / ou uso do Programa for restrito em determinados países por qualquer motivo, o Licenciante pode adicionar uma limitação de distribuição geográfica explícita excluindo esses países, de forma que a distribuição seja permitida apenas em ou entre países não excluídos. Nesse caso, esta Licença incorpora a limitação como se estivesse escrita no corpo desta Licença.
    5. Limitações.
    O PROGRAMA É FORNECIDO A VOCÊ "COMO ESTÁ", SEM GARANTIA. NÃO HÁ GARANTIA PARA O PROGRAMA, SEJA EXPRESSA OU IMPLÍCITA, INCLUINDO, MAS NÃO SE LIMITANDO A, GARANTIAS IMPLÍCITAS DE COMERCIALIZAÇÃO E ADEQUAÇÃO A UM DETERMINADO FIM E NÃO VIOLAÇÃO DE DIREITOS DE TERCEIROS. O RISCO TOTAL QUANTO À QUALIDADE E AO DESEMPENHO DO PROGRAMA É DE SUA RESPONSABILIDADE. CASO O PROGRAMA SE MOSTRE DEFEITUOSO, VOCÊ ASSUME OS CUSTOS DE TODOS OS SERVIÇOS, REPAROS OU CORREÇÕES NECESSÁRIOS.

    EM NENHUM CASO, A MENOS QUE EXIGIDO PELA LEI APLICÁVEL OU ACORDADO POR ESCRITO, O LICENCIANTE, OU QUALQUER OUTRA PARTE QUE POSSA MODIFICAR E / OU REDISTRIBUIR O PROGRAMA CONFORME PERMITIDO ACIMA, SERÁ RESPONSÁVEL POR DANOS, INCLUINDO QUAISQUER DANOS GERAIS, ESPECIAIS, INCIDENTAIS DECORRENTE DO USO OU DA INCAPACIDADE DE USAR O PROGRAMA (INCLUINDO, MAS NÃO SE LIMITANDO À PERDA DE DADOS OU DADOS SENDO PRESTADOS DE FORMA IMPRECISA OU PERDAS SUSTENTADAS POR VOCÊ OU TERCEIROS OU FALHA DO PROGRAMA PARA OPERAR COM QUAISQUER OUTROS PROGRAMAS), MESMO SE TAIS O TITULAR OU OUTRA PARTE FOI AVISADA DA POSSIBILIDADE DE TAIS DANOS.
    6. Geral.

    Esta Licença é regida pelas leis do Estado da Califórnia, EUA, excluindo a escolha das regras da lei.

    Se alguma parte desta Licença estiver em conflito com a lei, essa parte deve ser interpretada em seu significado mais amplo, consistente com a lei, e nenhuma outra parte da Licença será afetada.

    Para usuários do Governo dos Estados Unidos, o Programa é fornecido com DIREITOS RESTRITOS. Se você for uma unidade ou agência do Governo dos Estados Unidos ou estiver adquirindo o Programa para qualquer unidade ou agência, o seguinte se aplica:

    Se a unidade ou agência for o Departamento de Defesa ("DOD"), o Programa e sua documentação são classificados como "software de computador comercial" e "documentação de software de computador comercial" respectivamente e, de acordo com DFAR Seção 227.7202, o Governo está adquirindo o Programa e sua documentação de acordo com os termos desta Licença. Se a unidade ou agência for diferente do DOD, o Programa e sua documentação são classificados como "software de computador comercial" e "documentação de software de computador comercial" respectivamente e, de acordo com o FAR Seção 12.212, o Governo está adquirindo o Programa e sua documentação de acordo com os termos desta Licença.

